[target.msp430-none-elf]
# For debugging
# runner = "msp430-elf-gdb -q -x mspdebug.gdb"
# For running
runner = "./run.bat"

rustflags = [
    "-C", "link-arg=-nostartfiles",
    "-C", "link-arg=-Tlink.x",
    "-C", "link-arg=-lgcc",
    "-C", "link-arg=-lmul_32",
    "-C", "link-arg=-Wl,--allow-multiple-definition", # Prevent __muldi3 dupe errors
    "-C", "link-arg=-mcpu=msp430",
]

[build]
target = "msp430-none-elf"

[unstable]
# MSP430 doesn't come with libcore compiled already. But when it does, this
# key can be removed.
build-std = ["core"]
